Models/Professores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompareAttribute = System.Web.Mvc.CompareAttribute;

namespace AulaNeri2.Models
{
    public class Professores
    {
        [Display(Name = "Código")]
        [HiddenInput(DisplayValue =false)]
        public int profCodigo { get; set; }
        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Nome requerido")]
        public string profNome { get; set; }
        [Display(Name = "Curso que ele ministra")]
        [Required(ErrorMessage = "Curso requerido")]
        public string profCurso { get; set; }

        [Range(16,40,ErrorMessage ="A idade não está dentro do range permitido")]
        public int profIdade { get; set; }
        [DisplayFormat(DataFormatString ="dd/mm/yyyy")]
        public string profDatata { get; set; }

        [DataType(DataType.Password)]
        public string profSenha { get; set; }
        [DataType(DataType.Password)]
        [Compare("profSenha",ErrorMessage ="As senhas não conferem")]
        public string profSenha2 { get; set; }
    }
}

Controllers/ProfessoresController.cs
using AulaNeri2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AulaNeri2.Controllers
{
    public class ProfessoresController : Controller
    {
        private ProfessoresCrud profcrud;
        public ProfessoresController()
        {
            profcrud = ProfessoresFactory.InstanciarProfessores();
        }
        // GET: Professores
        public ActionResult Index()//Listar todos
        {
            //var professores = ProfessoresCrud.ListaProfessores(); Listar todos
            var professores = profcrud.ListaProfessores();
            return View(professores);
        }
        public ActionResult ListaUm()
        {
            //var professores = ProfessoresCrud.ListaProfessores()[0]; //Listar somente o índice
            var professores = profcrud.ListaProfessores()[1];
            return View(professores);
        }

        public ActionResult NovoProfessor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult NovoProfessor(Professores professor)
        {
            //var ultimoProfessor = ProfessoresFactory.InstanciarProfessores().ListaProfessores().
            //                        OrderByDescending(prof => prof.profCodigo).FirstOrDefault();//peguei o último código
            //professor.profCodigo = ultimoProfessor.profCodigo + 1;
            //ProfessoresFactory.InstanciarProfessores().InserirProfessor(professor);
            //var professores = ProfessoresFactory.InstanciarProfessores().ListaProfessores();

            if (ModelState.IsValid)
            {
                TempData["mensagem"] = "Professor gravado com sucesso";

                var ultimoProfessor = profcrud.ListaProfessores().
                                        OrderByDescending(prof => prof.profCodigo).FirstOrDefault();//peguei o último código
                professor.profCodigo = ultimoProfessor.profCodigo + 1;
                profcrud.InserirProfessor(professor);
                var professores = profcrud.ListaProfessores();
                return View("Index", professores);
            }
            else
                return View();

        }
        public ActionResult EditarProfessor(int id)
        {
            //var qualProfessor = profcrud.ListaProfessores()[id];
            var qualProfessor = profcrud.ListaProfessores().Where(prof => prof.profCodigo == id).FirstOrDefault();
            return View(qualProfessor);
        }
        [HttpPost]
        public ActionResult EditarProfessor(Professores professor)
        {
            if (ModelState.IsValid)
            {
                profcrud.AlterarProfessor(professor);
                var professores = profcrud.ListaProfessores();

                TempData["mensagem"] = "Professor alterado com sucesso";
                return View("Index", professores);
            }
            else
                return View();

        }
        public ActionResult ExcluirProfessor(int id)
        {
            //var qualProfessor = profcrud.ListaProfessores()[id];
            var qualProfessor = profcrud.ListaProfessores().Where(prof => prof.profCodigo == id).FirstOrDefault();
            return View(qualProfessor);
        }
        [HttpPost]
        public ActionResult ExcluirProfessorSim(Professores professor)
        {
            profcrud.excluirProfessor(professor);
            var professores = profcrud.ListaProfessores();
            TempData["mensagem"] = "Professor foi excluído";
            return View("Index", professores);
        }
    }
}

Views/Professores/EditarProfessor.cshtml
@model AulaNeri2.Models.Professores
@{
    ViewBag.Title = "Editar Professor";
}

<h2>Alteração de professor</h2>
@using (Html.BeginForm())
{
    <p>@Html.ValidationSummary(false, "Compos inválidos")</p>
    @Html.EditorForModel()

    <!--@Html.HiddenFor(professor => professor.profCodigo)

    <div class="editor-label">
            @Html.LabelFor(professor => professor.profNome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(professor => professor.profNome)
        </div>
        <div class="editor-label">
            @Html.LabelFor(professor => professor.profCurso)
        </div>
        <div class="editor-field">
        @Html.EditorFor(professor => professor.profCurso)
        </div>-->
    <p><input type="submit" value="Alterar registro" /></p>
}

Views/Professores/ExcluirProfessor.cshtml
@model AulaNeri2.Models.Professores
@{
    ViewBag.Title = "Excluir Professor";
}

<h2>Exclusão de professor</h2>
@using (Html.BeginForm("ExcluirProfessorSim","Professores"))
{
    @Html.HiddenFor(professor => professor.profCodigo)

    <div>
        @Html.LabelFor(professor => professor.profCodigo)
        @Html.DisplayFor(professor => professor.profCodigo)
    </div>
    <div>
        @Html.LabelFor(professor => professor.profNome)
        @Html.DisplayFor(professor => professor.profNome)
    </div>
    <div>
        @Html.LabelFor(professor => professor.profCurso)
        @Html.DisplayFor(professor => professor.profCurso)
    </div>
    <p><input type="submit" value="Excluir esse professor" /></p>
}

Views/Professores/Index.cshtml
@model List<AulaNeri2.Models.Professores>
@{
    ViewBag.Title = "Index";
}

<h2>
    @if (TempData["mensagem"] != null)
    {
        @TempData["mensagem"]
    }

</h2>
<p>Lista todos os professores</p>

<div>
    @Html.ActionLink("Cadastrar novo professor", "NovoProfessor")
</div>
<table>
    <tr>
        <th>Códido do Professor</th>
        <th>Nome do Professor</th>
        <th>Curso do Professor</th>
        <th>Exclusão</th>
        <th>Alteração</th>
    </tr>
    @foreach (var Professores in Model)
    {
        <tr>
            <td>@Html.DisplayFor(profCodigo => Professores.profCodigo)</td>
            <td>@Html.DisplayFor(profNome => Professores.profNome)</td>
            <td>@Html.DisplayFor(profCurso => Professores.profCurso)</td>
            <td>@Html.ActionLink("Excluir", "ExcluirProfessor", new { id = Professores.profCodigo })</td>
            <td>@Html.ActionLink("Editar", "EditarProfessor", new { id = Professores.profCodigo })</td>
        </tr>
    }
</table>

Views/Professores/ListaUm.cshtml
@model AulaNeri2.Models.Professores
@{
    ViewBag.Title = "ListaUm";
}

<h2>Lista um Professor</h2>

<table>
    <tr>
        <th>Códido do Professor</th>
        <th>Nome do Professor</th>
        <th>Curso do Professor</th>
    </tr>
    <tr>
        <td>@Html.DisplayFor(profCodigo => profCodigo.profCodigo)</td>
        <td>@Html.DisplayFor(profNome => profNome.profNome)</td>
        <td>@Html.DisplayFor(profCurso => profCurso.profCurso)</td>
    </tr>
</table>

Views/Professores/NovoProfessor.cshtml
@model AulaNeri2.Models.Professores
@{
    ViewBag.Title = "NovoProfessor";
}

<h2>Cadastro de novo professor</h2>
@using (Html.BeginForm())
{

    <p>@Html.ValidationSummary(false, "Compos inválidos")</p>
    @Html.EditorForModel();
    <!-- <div>
        @Html.LabelFor(professor => professor.profCodigo)
        @Html.EditorFor(professor => professor.profCodigo)
    </div>
    <div>
        @Html.LabelFor(professor => professor.profNome)
        @Html.EditorFor(professor => professor.profNome)
    </div>
    <div>
        @Html.LabelFor(professor => professor.profCurso)
        @Html.EditorFor(professor => professor.profCurso)
    </div>-->
    <p><input type="submit" value="Gravar registro" /></p>
}